package tables

// CreatePreferencesTable inserts the admin user
var CreatePreferencesTable = migrateTable(
	"CREATE_PREFERENCES_TABLE",
	"preferences",
	[]string{
		"CREATE TABLE public.preferences",
		"(",
		"    id uuid NOT NULL DEFAULT uuid_generate_v4(),",
		"    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,",
		"    updated_at timestamp with time zone NOT NULL,",
		"    deleted_at timestamp with time zone,",
		"    user_id uuid NOT NULL,",
		"    enable_auto_skip boolean,",
		"    enable_auto_play boolean,",
		"    skip_branding boolean,",
		"    skip_intros boolean,",
		"    skip_new_intros booleane,",
		"    skip_mixed_intros booleane,",
		"    skip_recaps boolean,",
		"    skip_filler boolean,",
		"    skip_canon booleane,",
		"    skip_transitions boolean,",
		"    skip_credits boolean,",
		"    skip_new_credits booleane,",
		"    skip_mixed_credits booleane,",
		"    skip_preview boolean,",
		"    skip_title_card boolean,",
		"    CONSTRAINT preferences_pkey PRIMARY KEY (id)",
		")",
		"WITH (",
		"    OIDS = FALSE",
		")",
		"TABLESPACE pg_default;",
	},
)
