#!/bin/bash
echo "LOG_LEVEL=0
LOG_SQL=false
ENABLE_INTROSPECTION=true
ENABLE_PLAYGROUND=true
IS_DEV=true
JWT_SECRET=1234

POSTGRES_DISABLE_SSL=true
POSTGRES_HOST=localhost
POSTGRES_PORT=5432
POSTGRES_USER=postgres
POSTGRES_PASSWORD=1234
POSTGRES_DBNAME=anime_skip_local
POSTGRES_ENABLE_SEEDING=true

DISABLE_EMAILS=false
EMAIL_SERVICE_HOST=not.anime-skip.com
EMAIL_SERVICE_SECRET=1234
EMAIL_ALLOWLIST=no.allowlist
USE_EMAIL_ALLOWLIST=false

RECAPTCHA_SECRET=1234
RECAPTCHA_RESPONSE_ALLOWLIST=1234

BETTER_VRV_APP_ID=1234
BETTER_VRV_API_KEY=1234" > .env
