services:
  # Server
  public_api:
    build:
      context: .
      args:
        VERSION: $VERSION-local
        STAGE: development
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - LOG_LEVEL=0
      - DATABASE_URL=postgres://postgres:password@postgres:5432/timestamps
      - DATABASE_DISABLE_SSL=true
      - DATABASE_VERSION=21
      - DATABASE_ENABLE_SEEDING=true
      - ENABLE_INTROSPECTION=true
      - ENABLE_PLAYGROUND=true
      - JWT_SECRET=some-secret
      - EMAIL_SERVICE_HOST=email-service
      - EMAIL_SERVICE_SECRET=some-secret
      - EMAIL_SERVICE_ENABLED=true
      - RECAPTCHA_SECRET=some-secret
      - RECAPTCHA_RESPONSE_ALLOWLIST=password1,password2
      - IS_SHOW_ADMIN_DISABLED=true
    env_file: .env

  # Dependencies
  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: timestamps
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 0.5s
      timeout: 0s
      retries: 10
    # logging:
    #     driver: none
      
  postgres_ui:
    image: sosedoff/pgweb
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    ports:
      - 9001:8081
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/timestamps?sslmode=disable
    logging:
        driver: none

  email-service:
    image: ealen/echo-server
