version: '3.8'

services:
  db:
    image: postgres:alpine
    command: -p 9000
    ports:
      - 9000:9000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: anime_skip_local
