package internal

const (
	ROLE_DEV   = 0
	ROLE_ADMIN = 1
	ROLE_USER  = 2
)

const (
	THEME_PER_SERVICE        = 0
	THEME_ANIME_SKIP_BLUE    = 1
	THEME_VRV_YELLOW         = 2
	THEME_FUNIMATION_PURPLE  = 3
	THEME_CRUNCHYROLL_ORANGE = 4
)

const (
	EPISODE_SOURCE_UNKNOWN     = 0
	EPISODE_SOURCE_VRV         = 1
	EPISODE_SOURCE_FUNIMATION  = 2
	EPISODE_SOURCE_CRUNCHYROLL = 3
)

const (
	TIMESTAMP_SOURCE_ANIME_SKIP = 0
	TIMESTAMP_SOURCE_BETTER_VRV = 1
)

const (
	TEMPLATE_TYPE_SHOW    = 0
	TEMPLATE_TYPE_SEASONS = 1
)
