// Code generated by cmd/sqlgen/main.go, DO NOT EDIT.

package postgres

import (
	internal "anime-skip.com/timestamps-service/internal"
	context1 "anime-skip.com/timestamps-service/internal/context"
	"context"
	"fmt"
	uuid "github.com/gofrs/uuid"
	sqlx "github.com/jmoiron/sqlx"
	"time"
)

func getEpisodeByID(ctx context.Context, db internal.Database, id uuid.UUID) (internal.Episode, error) {
	var episode internal.Episode
	err := db.GetContext(ctx, &episode, "SELECT * FROM episodes WHERE id=$1", id)
	return episode, err
}

func getEpisodesByShowID(ctx context.Context, db internal.Database, showID uuid.UUID) ([]internal.Episode, error) {
	rows, err := db.QueryxContext(ctx, "SELECT * FROM episodes WHERE deleted_at IS NULL")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	episodes := []internal.Episode{}
	for rows.Next() {
		var episode internal.Episode
		err = rows.StructScan(&episode)
		if err != nil {
			return nil, err
		}
		episodes = append(episodes, episode)
	}
	return episodes, nil
}

func getUnscopedEpisodesByShowID(ctx context.Context, db internal.Database, showID uuid.UUID) ([]internal.Episode, error) {
	rows, err := db.QueryxContext(ctx, "SELECT * FROM episodes")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	episodes := []internal.Episode{}
	for rows.Next() {
		var episode internal.Episode
		err = rows.StructScan(&episode)
		if err != nil {
			return nil, err
		}
		episodes = append(episodes, episode)
	}
	return episodes, nil
}

func insertEpisodeInTx(ctx context.Context, tx *sqlx.Tx, episode internal.Episode) (internal.Episode, error) {
	newEpisode := episode
	auth, err := context1.GetAuthenticationDetails(ctx)
	if err != nil {
		return internal.Episode{}, err
	}
	newEpisode.CreatedAt = time.Now()
	newEpisode.CreatedByUserID = auth.UserID
	newEpisode.UpdatedAt = time.Now()
	newEpisode.UpdatedByUserID = auth.UserID
	newEpisode.DeletedAt = nil
	newEpisode.DeletedByUserID = nil
	result, err := tx.ExecContext(
		ctx,
		"INSERT INTO episodes(id, created_at, created_by_user_id, updated_at, updated_by_user_id, deleted_at, deleted_by_user_id, season, number, absolute_number, name, base_duration, show_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)",
		newEpisode.ID, newEpisode.CreatedAt, newEpisode.CreatedByUserID, newEpisode.UpdatedAt, newEpisode.UpdatedByUserID, newEpisode.DeletedAt, newEpisode.DeletedByUserID, newEpisode.Season, newEpisode.Number, newEpisode.AbsoluteNumber, newEpisode.Name, newEpisode.BaseDuration, newEpisode.ShowID,
	)
	if err != nil {
		return internal.Episode{}, err
	}
	changedRows, err := result.RowsAffected()
	if err != nil {
		return internal.Episode{}, err
	}
	if changedRows != 1 {
		return internal.Episode{}, fmt.Errorf("Inserted more than 1 row (%d)", changedRows)
	}
	return newEpisode, err
}

func insertEpisode(ctx context.Context, db internal.Database, episode internal.Episode) (internal.Episode, error) {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return internal.Episode{}, err
	}
	defer tx.Rollback()

	result, err := insertEpisodeInTx(ctx, tx, episode)
	if err != nil {
		return internal.Episode{}, err
	}

	tx.Commit()
	return result, nil
}

func updateEpisodeInTx(ctx context.Context, tx *sqlx.Tx, newEpisode internal.Episode) (internal.Episode, error) {
	updatedEpisode := newEpisode
	auth, err := context1.GetAuthenticationDetails(ctx)
	if err != nil {
		return internal.Episode{}, err
	}
	updatedEpisode.UpdatedAt = time.Now()
	updatedEpisode.UpdatedByUserID = auth.UserID
	result, err := tx.ExecContext(
		ctx,
		"UPDATE episodes SET id=$1, created_at=$2, created_by_user_id=$3, updated_at=$4, updated_by_user_id=$5, deleted_at=$6, deleted_by_user_id=$7, season=$8, number=$9, absolute_number=$10, name=$11, base_duration=$12, show_id=$13",
		updatedEpisode.ID, updatedEpisode.CreatedAt, updatedEpisode.CreatedByUserID, updatedEpisode.UpdatedAt, updatedEpisode.UpdatedByUserID, updatedEpisode.DeletedAt, updatedEpisode.DeletedByUserID, updatedEpisode.Season, updatedEpisode.Number, updatedEpisode.AbsoluteNumber, updatedEpisode.Name, updatedEpisode.BaseDuration, updatedEpisode.ShowID,
	)
	if err != nil {
		return internal.Episode{}, err
	}
	changedRows, err := result.RowsAffected()
	if err != nil {
		return internal.Episode{}, err
	}
	if changedRows != 1 {
		return internal.Episode{}, fmt.Errorf("Updated more than 1 row (%d)", changedRows)
	}
	return updatedEpisode, err
}

func updateEpisode(ctx context.Context, db internal.Database, episode internal.Episode) (internal.Episode, error) {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return internal.Episode{}, err
	}
	defer tx.Rollback()

	result, err := updateEpisodeInTx(ctx, tx, episode)
	if err != nil {
		return internal.Episode{}, err
	}

	tx.Commit()
	return result, nil
}

func deleteEpisodeInTx(ctx context.Context, tx *sqlx.Tx, newEpisode internal.Episode) (internal.Episode, error) {
	deletedEpisode := newEpisode
	auth, err := context1.GetAuthenticationDetails(ctx)
	if err != nil {
		return internal.Episode{}, err
	}
	deletedEpisode.UpdatedAt = time.Now()
	deletedEpisode.UpdatedByUserID = auth.UserID
	now := time.Now()
	deletedEpisode.DeletedAt = &now
	deletedEpisode.DeletedByUserID = &auth.UserID
	result, err := tx.ExecContext(ctx, "DELETE FROM episodes WHERE id=$1", deletedEpisode.ID)
	if err != nil {
		return internal.Episode{}, err
	}
	changedRows, err := result.RowsAffected()
	if err != nil {
		return internal.Episode{}, err
	}
	if changedRows != 1 {
		return internal.Episode{}, fmt.Errorf("Deleted more than 1 row (%d)", changedRows)
	}
	return deletedEpisode, err
}

func deleteEpisode(ctx context.Context, db internal.Database, episode internal.Episode) (internal.Episode, error) {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return internal.Episode{}, err
	}
	defer tx.Rollback()

	result, err := deleteEpisodeInTx(ctx, tx, episode)
	if err != nil {
		return internal.Episode{}, err
	}

	tx.Commit()
	return result, nil
}
