// Code generated by cmd/sqlgen/main.go, DO NOT EDIT.

package postgres

import (
	internal "anime-skip.com/timestamps-service/internal"
	errors1 "anime-skip.com/timestamps-service/internal/errors"
	"context"
	"database/sql"
	"errors"
	"fmt"
	uuid "github.com/gofrs/uuid"
	"time"
)

func getPreferencesByID(ctx context.Context, db internal.Database, id uuid.UUID) (internal.Preferences, error) {
	var preferences internal.Preferences
	err := db.GetContext(ctx, &preferences, "SELECT * FROM preferences WHERE id=$1", id)
	if errors.Is(err, sql.ErrNoRows) {
		return internal.Preferences{}, errors1.NewRecordNotFound(fmt.Sprintf("Preferences.id=%s", id))
	}
	return preferences, err
}

func getPreferencesByUserID(ctx context.Context, db internal.Database, userID uuid.UUID) (internal.Preferences, error) {
	var preferences internal.Preferences
	err := db.GetContext(ctx, &preferences, "SELECT * FROM preferences WHERE user_id=$1 AND deleted_at IS NULL", userID)
	if errors.Is(err, sql.ErrNoRows) {
		return internal.Preferences{}, errors1.NewRecordNotFound(fmt.Sprintf("Preferences.userID=%s", userID))
	}
	return preferences, err
}

func getUnscopedPreferencesByUserID(ctx context.Context, db internal.Database, userID uuid.UUID) (internal.Preferences, error) {
	var preferences internal.Preferences
	err := db.GetContext(ctx, &preferences, "SELECT * FROM preferences WHERE user_id=$1", userID)
	if errors.Is(err, sql.ErrNoRows) {
		return internal.Preferences{}, errors1.NewRecordNotFound(fmt.Sprintf("Preferences.userID=%s", userID))
	}
	return preferences, err
}

func insertPreferencesInTx(ctx context.Context, tx internal.Tx, preferences internal.Preferences) (internal.Preferences, error) {
	newPreferences := preferences
	newPreferences.CreatedAt = time.Now()
	newPreferences.UpdatedAt = time.Now()
	newPreferences.DeletedAt = nil
	result, err := tx.ExecContext(
		ctx,
		"INSERT INTO preferences(id, created_at, updated_at, deleted_at, user_id, enable_auto_skip, enable_auto_play, minimize_toolbar_when_editing, hide_timeline_when_minimized, color_theme, skip_branding, skip_intros, skip_new_intros, skip_mixed_intros, skip_recaps, skip_filler, skip_canon, skip_transitions, skip_credits, skip_new_credits, skip_mixed_credits, skip_preview, skip_title_card) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23)",
		newPreferences.ID, newPreferences.CreatedAt, newPreferences.UpdatedAt, newPreferences.DeletedAt, newPreferences.UserID, newPreferences.EnableAutoSkip, newPreferences.EnableAutoPlay, newPreferences.MinimizeToolbarWhenEditing, newPreferences.HideTimelineWhenMinimized, newPreferences.ColorTheme, newPreferences.SkipBranding, newPreferences.SkipIntros, newPreferences.SkipNewIntros, newPreferences.SkipMixedIntros, newPreferences.SkipRecaps, newPreferences.SkipFiller, newPreferences.SkipCanon, newPreferences.SkipTransitions, newPreferences.SkipCredits, newPreferences.SkipNewCredits, newPreferences.SkipMixedCredits, newPreferences.SkipPreview, newPreferences.SkipTitleCard,
	)
	if err != nil {
		return internal.Preferences{}, err
	}
	changedRows, err := result.RowsAffected()
	if err != nil {
		return internal.Preferences{}, err
	}
	if changedRows != 1 {
		return internal.Preferences{}, fmt.Errorf("Inserted more than 1 row (%d)", changedRows)
	}
	return newPreferences, err
}

func insertPreferences(ctx context.Context, db internal.Database, preferences internal.Preferences) (internal.Preferences, error) {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return internal.Preferences{}, err
	}
	defer tx.Rollback()

	result, err := insertPreferencesInTx(ctx, tx, preferences)
	if err != nil {
		return internal.Preferences{}, err
	}

	tx.Commit()
	return result, nil
}

func updatePreferencesInTx(ctx context.Context, tx internal.Tx, newPreferences internal.Preferences) (internal.Preferences, error) {
	updatedPreferences := newPreferences
	updatedPreferences.UpdatedAt = time.Now()
	result, err := tx.ExecContext(
		ctx,
		"UPDATE preferences SET id=$1, created_at=$2, updated_at=$3, deleted_at=$4, user_id=$5, enable_auto_skip=$6, enable_auto_play=$7, minimize_toolbar_when_editing=$8, hide_timeline_when_minimized=$9, color_theme=$10, skip_branding=$11, skip_intros=$12, skip_new_intros=$13, skip_mixed_intros=$14, skip_recaps=$15, skip_filler=$16, skip_canon=$17, skip_transitions=$18, skip_credits=$19, skip_new_credits=$20, skip_mixed_credits=$21, skip_preview=$22, skip_title_card=$23",
		updatedPreferences.ID, updatedPreferences.CreatedAt, updatedPreferences.UpdatedAt, updatedPreferences.DeletedAt, updatedPreferences.UserID, updatedPreferences.EnableAutoSkip, updatedPreferences.EnableAutoPlay, updatedPreferences.MinimizeToolbarWhenEditing, updatedPreferences.HideTimelineWhenMinimized, updatedPreferences.ColorTheme, updatedPreferences.SkipBranding, updatedPreferences.SkipIntros, updatedPreferences.SkipNewIntros, updatedPreferences.SkipMixedIntros, updatedPreferences.SkipRecaps, updatedPreferences.SkipFiller, updatedPreferences.SkipCanon, updatedPreferences.SkipTransitions, updatedPreferences.SkipCredits, updatedPreferences.SkipNewCredits, updatedPreferences.SkipMixedCredits, updatedPreferences.SkipPreview, updatedPreferences.SkipTitleCard,
	)
	if err != nil {
		return internal.Preferences{}, err
	}
	changedRows, err := result.RowsAffected()
	if err != nil {
		return internal.Preferences{}, err
	}
	if changedRows != 1 {
		return internal.Preferences{}, fmt.Errorf("Updated more than 1 row (%d)", changedRows)
	}
	return updatedPreferences, err
}

func updatePreferences(ctx context.Context, db internal.Database, preferences internal.Preferences) (internal.Preferences, error) {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return internal.Preferences{}, err
	}
	defer tx.Rollback()

	result, err := updatePreferencesInTx(ctx, tx, preferences)
	if err != nil {
		return internal.Preferences{}, err
	}

	tx.Commit()
	return result, nil
}

func deletePreferencesInTx(ctx context.Context, tx internal.Tx, newPreferences internal.Preferences) (internal.Preferences, error) {
	deletedPreferences := newPreferences
	deletedPreferences.UpdatedAt = time.Now()
	now := time.Now()
	deletedPreferences.DeletedAt = &now
	result, err := tx.ExecContext(ctx, "DELETE FROM preferences WHERE id=$1", deletedPreferences.ID)
	if err != nil {
		return internal.Preferences{}, err
	}
	changedRows, err := result.RowsAffected()
	if err != nil {
		return internal.Preferences{}, err
	}
	if changedRows != 1 {
		return internal.Preferences{}, fmt.Errorf("Deleted more than 1 row (%d)", changedRows)
	}
	return deletedPreferences, err
}

func deletePreferences(ctx context.Context, db internal.Database, preferences internal.Preferences) (internal.Preferences, error) {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return internal.Preferences{}, err
	}
	defer tx.Rollback()

	result, err := deletePreferencesInTx(ctx, tx, preferences)
	if err != nil {
		return internal.Preferences{}, err
	}

	tx.Commit()
	return result, nil
}
