// Code generated by cmd/sqlgen/main.go, DO NOT EDIT.

package postgres

import (
	internal "anime-skip.com/timestamps-service/internal"
	context1 "anime-skip.com/timestamps-service/internal/context"
	errors1 "anime-skip.com/timestamps-service/internal/errors"
	"context"
	"database/sql"
	"errors"
	"fmt"
	uuid "github.com/gofrs/uuid"
	"time"
)

func getTemplateByIDInTx(ctx context.Context, tx internal.Tx, id uuid.UUID) (internal.Template, error) {
	var template internal.Template
	err := tx.GetContext(ctx, &template, "SELECT * FROM templates WHERE id=$1", id)
	if errors.Is(err, sql.ErrNoRows) {
		return internal.Template{}, errors1.NewRecordNotFound(fmt.Sprintf("Template.id=%s", id))
	}
	return template, err
}

func getTemplateByID(ctx context.Context, db internal.Database, ID uuid.UUID) (internal.Template, error) {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return internal.Template{}, err
	}
	defer tx.Rollback()

	result, err := getTemplateByIDInTx(ctx, tx, ID)
	if err != nil {
		return internal.Template{}, err
	}

	tx.Commit()
	return result, nil
}

func getTemplateBySourceEpisodeIDInTx(ctx context.Context, tx internal.Tx, sourceEpisodeID uuid.UUID) (internal.Template, error) {
	var template internal.Template
	err := tx.GetContext(ctx, &template, "SELECT * FROM templates WHERE source_episode_id=$1 AND deleted_at IS NULL", sourceEpisodeID)
	if errors.Is(err, sql.ErrNoRows) {
		return internal.Template{}, errors1.NewRecordNotFound(fmt.Sprintf("Template.sourceEpisodeID=%s", sourceEpisodeID))
	}
	return template, err
}

func getTemplateBySourceEpisodeID(ctx context.Context, db internal.Database, SourceEpisodeID uuid.UUID) (internal.Template, error) {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return internal.Template{}, err
	}
	defer tx.Rollback()

	result, err := getTemplateBySourceEpisodeIDInTx(ctx, tx, SourceEpisodeID)
	if err != nil {
		return internal.Template{}, err
	}

	tx.Commit()
	return result, nil
}

func getUnscopedTemplateBySourceEpisodeIDInTx(ctx context.Context, tx internal.Tx, sourceEpisodeID uuid.UUID) (internal.Template, error) {
	var template internal.Template
	err := tx.GetContext(ctx, &template, "SELECT * FROM templates WHERE source_episode_id=$1", sourceEpisodeID)
	if errors.Is(err, sql.ErrNoRows) {
		return internal.Template{}, errors1.NewRecordNotFound(fmt.Sprintf("Template.sourceEpisodeID=%s", sourceEpisodeID))
	}
	return template, err
}

func getUnscopedTemplateBySourceEpisodeID(ctx context.Context, db internal.Database, SourceEpisodeID uuid.UUID) (internal.Template, error) {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return internal.Template{}, err
	}
	defer tx.Rollback()

	result, err := getUnscopedTemplateBySourceEpisodeIDInTx(ctx, tx, SourceEpisodeID)
	if err != nil {
		return internal.Template{}, err
	}

	tx.Commit()
	return result, nil
}

func getTemplatesByShowIDInTx(ctx context.Context, tx internal.Tx, showID uuid.UUID) ([]internal.Template, error) {
	rows, err := tx.QueryxContext(ctx, "SELECT * FROM templates WHERE deleted_at IS NULL")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	templates := []internal.Template{}
	for rows.Next() {
		var template internal.Template
		err = rows.StructScan(&template)
		if err != nil {
			return nil, err
		}
		templates = append(templates, template)
	}
	return templates, nil
}

func getTemplatesByShowID(ctx context.Context, db internal.Database, ShowID uuid.UUID) ([]internal.Template, error) {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	result, err := getTemplatesByShowIDInTx(ctx, tx, ShowID)
	if err != nil {
		return nil, err
	}

	tx.Commit()
	return result, nil
}

func getUnscopedTemplatesByShowIDInTx(ctx context.Context, tx internal.Tx, showID uuid.UUID) ([]internal.Template, error) {
	rows, err := tx.QueryxContext(ctx, "SELECT * FROM templates")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	templates := []internal.Template{}
	for rows.Next() {
		var template internal.Template
		err = rows.StructScan(&template)
		if err != nil {
			return nil, err
		}
		templates = append(templates, template)
	}
	return templates, nil
}

func getUnscopedTemplatesByShowID(ctx context.Context, db internal.Database, ShowID uuid.UUID) ([]internal.Template, error) {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	result, err := getUnscopedTemplatesByShowIDInTx(ctx, tx, ShowID)
	if err != nil {
		return nil, err
	}

	tx.Commit()
	return result, nil
}

func insertTemplateInTx(ctx context.Context, tx internal.Tx, template internal.Template) (internal.Template, error) {
	newTemplate := template
	claims, err := context1.GetAuthClaims(ctx)
	if err != nil {
		return internal.Template{}, err
	}
	now := time.Now()
	newTemplate.CreatedAt = now
	newTemplate.CreatedByUserID = claims.UserID
	newTemplate.UpdatedAt = now
	newTemplate.UpdatedByUserID = claims.UserID
	newTemplate.DeletedAt = nil
	newTemplate.DeletedByUserID = nil
	result, err := tx.ExecContext(
		ctx,
		"INSERT INTO templates(id, created_at, created_by_user_id, updated_at, updated_by_user_id, deleted_at, deleted_by_user_id, show_id, type, seasons, source_episode_id) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)",
		newTemplate.ID, newTemplate.CreatedAt, newTemplate.CreatedByUserID, newTemplate.UpdatedAt, newTemplate.UpdatedByUserID, newTemplate.DeletedAt, newTemplate.DeletedByUserID, newTemplate.ShowID, newTemplate.Type, newTemplate.Seasons, newTemplate.SourceEpisodeID,
	)
	if err != nil {
		return internal.Template{}, err
	}
	changedRows, err := result.RowsAffected()
	if err != nil {
		return internal.Template{}, err
	}
	if changedRows != 1 {
		return internal.Template{}, fmt.Errorf("Inserted more than 1 row (%d)", changedRows)
	}
	return newTemplate, err
}

func insertTemplate(ctx context.Context, db internal.Database, template internal.Template) (internal.Template, error) {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return internal.Template{}, err
	}
	defer tx.Rollback()

	result, err := insertTemplateInTx(ctx, tx, template)
	if err != nil {
		return internal.Template{}, err
	}

	tx.Commit()
	return result, nil
}

func updateTemplateInTx(ctx context.Context, tx internal.Tx, newTemplate internal.Template) (internal.Template, error) {
	updatedTemplate := newTemplate
	claims, err := context1.GetAuthClaims(ctx)
	if err != nil {
		return internal.Template{}, err
	}
	now := time.Now()
	updatedTemplate.UpdatedAt = now
	updatedTemplate.UpdatedByUserID = claims.UserID
	result, err := tx.ExecContext(
		ctx,
		"UPDATE templates SET created_at=$1, created_by_user_id=$2, updated_at=$3, updated_by_user_id=$4, deleted_at=$5, deleted_by_user_id=$6, show_id=$7, type=$8, seasons=$9, source_episode_id=$10 WHERE id = $11",
		updatedTemplate.CreatedAt, updatedTemplate.CreatedByUserID, updatedTemplate.UpdatedAt, updatedTemplate.UpdatedByUserID, updatedTemplate.DeletedAt, updatedTemplate.DeletedByUserID, updatedTemplate.ShowID, updatedTemplate.Type, updatedTemplate.Seasons, updatedTemplate.SourceEpisodeID, updatedTemplate.ID,
	)
	if err != nil {
		return internal.Template{}, err
	}
	changedRows, err := result.RowsAffected()
	if err != nil {
		return internal.Template{}, err
	}
	if changedRows != 1 {
		return internal.Template{}, fmt.Errorf("Updated more than 1 row (%d)", changedRows)
	}
	return updatedTemplate, err
}

func updateTemplate(ctx context.Context, db internal.Database, template internal.Template) (internal.Template, error) {
	tx, err := db.BeginTxx(ctx, nil)
	if err != nil {
		return internal.Template{}, err
	}
	defer tx.Rollback()

	result, err := updateTemplateInTx(ctx, tx, template)
	if err != nil {
		return internal.Template{}, err
	}

	tx.Commit()
	return result, nil
}

func deleteTemplateInTx(ctx context.Context, tx internal.Tx, newTemplate internal.Template) (internal.Template, error) {
	updatedTemplate := newTemplate
	claims, err := context1.GetAuthClaims(ctx)
	if err != nil {
		return internal.Template{}, err
	}
	now := time.Now()
	updatedTemplate.UpdatedAt = now
	updatedTemplate.UpdatedByUserID = claims.UserID
	updatedTemplate.DeletedAt = &now
	updatedTemplate.DeletedByUserID = &claims.UserID
	result, err := tx.ExecContext(
		ctx,
		"UPDATE templates SET created_at=$1, created_by_user_id=$2, updated_at=$3, updated_by_user_id=$4, deleted_at=$5, deleted_by_user_id=$6, show_id=$7, type=$8, seasons=$9, source_episode_id=$10 WHERE id = $11",
		updatedTemplate.CreatedAt, updatedTemplate.CreatedByUserID, updatedTemplate.UpdatedAt, updatedTemplate.UpdatedByUserID, updatedTemplate.DeletedAt, updatedTemplate.DeletedByUserID, updatedTemplate.ShowID, updatedTemplate.Type, updatedTemplate.Seasons, updatedTemplate.SourceEpisodeID, updatedTemplate.ID,
	)
	if err != nil {
		return internal.Template{}, err
	}
	changedRows, err := result.RowsAffected()
	if err != nil {
		return internal.Template{}, err
	}
	if changedRows != 1 {
		return internal.Template{}, fmt.Errorf("Updated more than 1 row (%d)", changedRows)
	}
	return updatedTemplate, err
}
