name: Deploy
on:
  push:
    branches:
      - master

jobs:

  heroku-push:
    name: Heroku
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/setup.yml
    - uses: ./.github/actions/build.yml
    - uses: ./.github/actions/deploy.yml
