name: Deploy
on:
  push:
    branches:
      - master

jobs:

  verify:
    name: Verify Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - uses: actions/checkout@v1
      - name: Create .env
        run: ./.github/create-env.sh
      - name: Build
        run: make build
      - name: Lint
        run: echo "TODO" # make lint
      - name: Run Tests
        run: make test
      - name: Run E2E Tests
        run: echo "TODO" # make e2e-test
  heroku-push:
    name: Push to Heroku
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v1
      - name: Deploy to Heroku
        if: github.ref == 'refs/heads/master' && job.status == 'success'
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: ./.github/deploy.sh
