name: Dev Release
on:
  push:
    # branches:
    #  - main

jobs:
  verify:
    name: Verify Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        run: ./.github/create-env.sh
      - name: Build
        run: make build
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Lint
        run: echo "TODO" # make lint
      - name: Run Tests
        run: make test
      - name: Run E2E Tests
        run: echo "TODO" # make e2e-test

  push_to_registry:
    name: Push dev image
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: anime-skip/backend/anime-skip-api
          tags: dev
