name: Dev Release
on:
  push:
    branch:
      - main

jobs:
  verify:
    name: Verify Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Create .env
        run: ./.github/create-env.sh
      - name: Build
        run: make build
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Lint
        run: echo "TODO" # make lint
      - name: Run Tests
        run: make test
      - name: Run E2E Tests
        run: echo "TODO" # make e2e-test
  
  dev_deploy:
    name: Deploy Dev
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v1
      - name: Build image
        run: docker build . --tag backend:dev
      - name: Push backend:dev
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          region: us-east-2
          image: backend:dev
