name: Prod Release
on:
  push:
    tags:
      - v*

jobs:
  prod_deploy:
    name: Deploy Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: olegtarasov/get-tag@v2
        id: tagName
        with:
          tagRegex: "v(.*)"
      - name: Build new images
        run: docker build . --tag backend:latest
      - name: Push latest to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          region: us-east-2
          image: backend:latest
      - name: Push ${{ steps.tagName.outputs.tag }} to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.ECR_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          region: us-east-2
          local-image: backend:latest
          image: backend:${{ steps.tagName.outputs.tag }}
          is-semver: true
