name: Prod Release
on:
  push:
    # tags:
    #   - v*

jobs:
  prod_deploy:
    name: Deploy Prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2
        id: tagName
        with:
          tagRegex: "v(.*)"
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: anime-skip/backend/anime-skip-api
          tags: prod
      - name: Deploy on Heroku
        uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: anime-skip-api
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          usedocker: true
