name: Prod Release

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: anime-skip/backend

jobs:
  promote:
    name: Promote to Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staged
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ""
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true
      - name: Promote staged to prod in GitHub Packages
        run: |
          set -eo pipefail
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u "${{ github.actor }}" --password-stdin "$REGISTRY"
          docker image tag ${{ STAGED_IMAGE }} ${{ PROD_IMAGE }}
          docker push ${{ PROD_IMAGE }}
        env:
          STAGED_IMAGE: docker.pkg.github.com/anime-skip/backend/api:staged
          PROD_IMAGE: docker.pkg.github.com/anime-skip/backend/api:prod
      - name: Promote staged to prod in Heroku
        run: |
          set -eo pipefail
          docker image tag $BASE_IMAGE $HEROKU_TAG_PROD
          docker image tag $BASE_IMAGE $HEROKU_TAG_TEST
          docker push -a
          heroku container:release web
        env:
          BASE_IMAGE: docker.pkg.github.com/anime-skip/backend/api:prod
          HEROKU_TAG_PROD: registry.heroku.com/staged-api-service/web
          HEROKU_TAG_TEST: registry.heroku.com/staged-api-test-service/web
  update_releases:

