name: Publish Staged
on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_REPO: anime-skip/backend

jobs:
  verify:
    name: Verify Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env
        run: ./.github/create-env.sh
      - name: Build
        run: make build
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Lint
        run: echo "TODO" # make lint
      - name: Run Tests
        run: make test
      - name: Run E2E Tests
        run: echo "TODO" # make e2e-test

  publish:
    name: Publish the :staged container
    runs-on: ubuntu-latest
    needs: verify
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staged
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ""
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true
      - name: Delete old Release/Tag
        run: |
          set -eo pipefail
          TAG=$(git --no-pager tag --points-at HEAD)
          gh release delete $TAG
          git tag -d $TAG
          git push --delete origin $TAG
      - name: Reset staged to main
        run: git reset --hard origin/main
      - name: Get Pre-conventional Commits Changelog
        id: old_changelog
        run: |
          set -eo pipefail
          git clone -–depth 1 git@github.com:anime-skip/backend.wiki.git wiki
          OLD_CHANGELOG=$(cat wiki/Pre-conventional-Commits-Changelog.md)
          rm -rf wiki
          echo "::set-output name=changelog::$(echo '$OLD_CHANGELOG')\n"
      - name: Bump Version and Changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: 'chore(release): Version {version}'
          output-file: CHANGELOG.md
          release-count: 0 # all
          version-file: ./meta.json
          version-path: version
          fallback-version: "1.0.9"
        env: 
          OLD_CHANGELOG: ${{ steps.old_changelog.outputs.changelog }}
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: anime-skip/backend/api
          tags: staged
      - name: Deploy staged.api.anime-skip.com
        run: |
          set -eo pipefail
          docker image tag $BASE_IMAGE $HEROKU_TAG
          docker push -a
          heroku container:release web
        env:
          BASE_IMAGE: docker.pkg.github.com/anime-skip/backend/api:staged
          HEROKU_TAG: registry.heroku.com/staged-api-service/web
