name: Verify PR
on:
  push:
    branches-ignore:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - uses: actions/checkout@v1
    - name: Build
      run: ./.github/build.sh
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - uses: actions/checkout@v1
    - name: Lint
      run: ./.github/lint.sh
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - uses: actions/checkout@v1
    - name: Run Tests
      run: ./.github/test.sh
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - uses: actions/checkout@v1
    - name: Run Tests
      run: ./.github/e2e-test.sh
