name: Verify PR
on:
  push:
    branches-ignore:
      - main
      - staged

jobs:
  verify:
    name: Verify Code
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Build
        run: make build

      - name: Lint
        run: echo "TODO" # make lint

      - name: Run Tests
        run: |
          ./.github/create-env.sh
          make test

      - name: Run E2E Tests
        run: echo "TODO" # make e2e-test
