name: Verify PR
on:
  push:
    branches-ignore:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - uses: actions/checkout@v1
    - name: Build
      run: ./.github/build.sh
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - uses: actions/checkout@v1
    - name: Build
      run: ./.github/build.sh
    - name: Tests
      run: echo "Test"
